### ISSUE TITLE
Can't resolve images from src directory [@plaiceholder/next]

### ISSUE THREAD

**Issue by paambaati** [joe-bell/plaiceholder#11]
**Describe the bug**
When following the example in the README, I see 2 issues —

1. The image actually doesn't work, and causes this error.

    <img width="992" alt="Screenshot 2020-11-26 at 8 47 50 PM" src="https://user-images.githubusercontent.com/5381764/100367831-cf51c600-3028-11eb-83d1-5b2c7a0ff274.png">

2. Once I've patched the above issue manually, I see this error.

    <img width="993" alt="Screenshot 2020-11-26 at 8 50 57 PM" src="https://user-images.githubusercontent.com/5381764/100368073-222b7d80-3029-11eb-98db-834a67c4109a.png">

**To Reproduce**

1. Follow the example in the README and run your Next.js app.
2. See the errors I reported.

**Expected behavior**
No errors should occur and the page should actually load.

**Screenshots**
(See above)

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.7
- Browser: Chrome 88.0.4324.11 (Dev Build)
- Version: 1.0.0

**Additional context**
The 2 issues are because —

1. The `public/` path you're resolving to doesn't support `src/`. Next.js supports `public` directory inside `src/` — see https://nextjs.org/docs/advanced-features/src-directory.
2. The `imgSrc` returned in your example as `props` should be the path to the image as a string, and not the `Buffer` returned from the `getImage()` method.

**Comment by joe-bell** [comment]
Thanks for raising! Will take a look at this next week

**Comment by joe-bell** [comment]
@paambaati actually come to think of it, I'm using `src` to build [Plaiceholder.co](https://plaiceholder.co) and it works perfectly fine

I think the problem here is that you're trying to use `public` inside `src`, which Next.js explicitly says [**is not** supported](https://nextjs.org/docs/advanced-features/src-directory)
>Config files like next.config.js and tsconfig.json should be inside the root directory, moving them to src won't work. Same goes for the public directory

Thanks for taking the time to write this up, but I think moving `public` to your project root should solve the issue 🙂
