### ISSUE TITLE
Increase max width

### ISSUE THREAD

**Issue by chris-makaio** [joe-bell/plaiceholder#111]
**Is your feature request related to a problem? Please describe.**
For bigger images it would be awesome to have size, eg, 128. I tried increasing sizeMax in get-image.ts but that results in " Maximum call stack size exceeded" - I guess there's a reason why you set it to 64 ;)

**Comment by joe-bell** [comment]
Hey @chris-makaio, thanks for taking the time to write this up!

Ha you are indeed correct that's why it's set to `64` – but also mostly because optimal placeholders are around `1` to `12` in size. Given this, I'm afraid this isn't such a huge priority for me right now

Can you tell me more about your use-case? Interested to hear more about why you need to create such large placeholders

**Comment by chris-makaio** [comment]
Thanks for the quick reply:)
Well, we have a stage slider which takes up the whole viewport above the fold with up to 5 large HD images.
Currently (We‘re using next and Strapi) we fetch the Strapi-generated thumbnail during SSR and use plaiceholder for the other images but it would help to use the same logic/flow for all images

**Comment by joe-bell** [comment]
No problem! So it's worth keeping in mind that `64` [produces **a lot** of CSS](https://twitter.com/joebell_/status/1397082424568332289) – so it's really not ideal for high-priority above-the-fold images

If this is what `64` looks like, imagine `128` 🥴 

For that reason I don't think I'd consider making the `size` bigger. I'd recommend using the defaults, but if you'd like a bit more fidelity to your placeholders I'd recommend not going further than `10`

---

P.S. Just to be clear–in case there's some confusion here–Plaiceholder supports any image size. The `size` param controls the output size, rather than the input size.

**Comment by chris-makaio** [comment]
Understood for CSS, but we‘ll use base64 ;)

**Comment by joe-bell** [comment]
Even for Base64, [size makes a **huge** difference](https://csswizardry.com/2017/02/base64-encoding-and-performance/) — same rules apply! 

You're much better off going for a low size with a large blur than a large size with a small blur 

So I probably wouldn't consider supporting anything larger than the boundaries that currently exist

**Comment by chris-makaio** [comment]
yeah, that makes sense - thanks!

**Comment by joe-bell** [comment]
No worries!
